config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    get 'print', to: 'orders#print'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cloud.rb
class Cloud < ApplicationRecord

  def init

  end

  gh = [0, 0, 1, 0, 0, 1, 0]

  def solution(c)
    count = 0
    c = c.split('1')


    c.each_with_index do |c, i|
      if (c.length > 1)
        jump = (c.length / 2.0).ceil
        if c.length % 2 == 0
          jump += 1
        end
        count += jump
      else
        count += 1
      end
    end
    count -= 1
    count
  end


end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/ransom_note.rb
class RansomNote < ApplicationRecord


  def solution(s, n)
    puts s
    puts n
    magazine = s.strip.split(' ')
    note = n.strip.split(' ')
    orig_l = magazine.length
    comp_l = note.length
    puts orig_l
    puts comp_l
    note.each do |n|
      magazine = magazine - [n]
    end
    puts magazine.length
    if orig_l - magazine.length == comp_l
      'Yes'
    else
      'No'
    end
  end
end

app/models/repeated_string.rb
class RepeatedString < ApplicationRecord

  def solution(s, n)
    count = 0
    str = s.split('')
    repeats = n / str.length
    remain = n - repeats * str.length
    count += str.count('a') * repeats
    unless n % str.length == 0
      count += str[0..remain - 1].count('a')
    end
    count
  end


end

app/models/two_string.rb
class TwoString < ApplicationRecord

  def solution(s, n)
    shared = s.split('') & n.split('')
    puts shared
    if shared.length > 0
      puts "Yes"
      "Yes"
    elsif n.split('').include?(s.split(''))
      puts "Yes"
      "Yes"
    else
      puts "No"
      "No"
    end


  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def print
    @order = Order.find(params[:order_id])
    respond_to do |format|
      format.html
      format.pdf do
        send_data PDFKit.new(render_to_string 'print', order: @order).to_pdf
        send_data(PDFKit.new(render_to_string 'print', order: @order).to_pdf, :disposition=> "attachment; filename=robots.zip")

      end
    end
  end

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html {redirect_to @order, notice: 'Order was successfully created.'}
        format.json {render :show, status: :created, location: @order}
      else
        format.html {render :new}
        format.json {render json: @order.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html {redirect_to @order, notice: 'Order was successfully updated.'}
        format.json {render :show, status: :ok, location: @order}
      else
        format.html {render :edit}
        format.json {render json: @order.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html {redirect_to orders_url, notice: 'Order was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:name, :thing)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hckerrank</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :thing %>
    <%= form.text_field :thing %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Thing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.thing %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/print.html.erb
<div style="display: inline-block">
  <table class="QR" style="width:100%">
    <tr style="margin:30px">
      <td class="QR">

      </td>
      <td style="font-size:50px;padding:20px; text-align:center">
        <%=@order.name%><br>
        <%=@order.thing%>
      </td>
    </tr>
  </table>
</div>

app/views/orders/print.pdf.erb
<div style="display: inline-block">
  <table class="QR" style="width:100%">
    <tr style="margin:30px">
      <td class="QR">

      </td>
      <td style="font-size:50px;padding:20px; text-align:center">
        <%=@order.name%><br>
        <%=@order.thing%>
      </td>
    </tr>
  </table>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Thing:</strong>
  <%= @order.thing %>
</p>
<%= link_to 'Print', order_print_path(@order, :format => :pdf) %> |

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>